root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to preprocessed data directory
preprocessed_dir: ${paths.root_dir}/data/preprocessed/

prediction_dir: ${paths.root_dir}/data/predicted_note_attrib
label_dir: ${paths.root_dir}/data/full_tatum_label_modified
full_label_dir: ${paths.root_dir}/data/full_label_modified
audio_dir: ${paths.root_dir}/data/wav

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}