_target_: src.dataset.dataset.SoloDatasetModule
data_dir: ${paths.data_dir}
train_test_split_ratio: 0.9
batch_size: 3
# cache_dataset: False
num_workers: ${local_env.n_workers}
#dataloader_workers: ${local_env.n_workers}
dataloader_workers: 0
pin_memory: False
persistent_workers: False
preprocess_on_training_start: True